T8S3-18 creacion model y repository Role
alkemyTech/OT8-3-Server pull request #10
Opened 2023-12-06 01:26 UTC by leorivero

no se porque en esta entidad cuando quise que haga la relación con el archivo Enum en el atributo name, me tomo toda la ruta y no el nombre solo como en otras entidades, ni se me importo arriba con las demás cosas

2023-12-06 15:15 UTC, Tilk1 commented
Eso pasa porque la clase del model Role  y el enum se llaman igual. Cambiale a las clases de los enums por la palabra Enum al final "RoleEnum"

2023-12-06 15:31 UTC, leorivero commented
listo ya lo subi con el archivo enum renombrado a RoleEnum

2023-12-06 17:08 UTC, Tilk1 requested changes
Falta la anotacion del @repository  para que compile  y cambia las demas clases que queden con Enum

2023-12-06 17:17 UTC, leorivero commented
> Falta la anotacion del @repository para que compile y cambia las demas clases que queden con Enum

Listo renombre los enum y agregue el repository

2023-12-07 01:59 UTC, Tilk1 commented
Los proximos models agregales @Data para los metodos del lombok

2023-12-07 01:59 UTC, merged