T8S3-27 endpoint listar cuentas por usuario
alkemyTech/OT8-3-Server pull request #13
Opened 2023-12-07 01:45 UTC by leorivero

2023-12-07 21:55 UTC, PsyBrainy requested changes

2023-12-07 21:55 UTC, PsyBrainy commented on src/main/java/com/alkemy/wallet/dto/AccountDto.java
> +    Currency currency;
los atributos deberían ser privados

2023-12-07 21:55 UTC, PsyBrainy commented on src/main/java/com/alkemy/wallet/dto/AccountDto.java
> +    User user;
faltarian los guetters y setters

2023-12-09 21:07 UTC, leorivero commented
![consulta get lista cuentas](https://github.com/alkemyTech/OT8-3-Server/assets/50146208/d5ed4eb0-769e-4a3a-a917-19fdeff41f85)

2023-12-11 18:24 UTC, PsyBrainy approved these changes

2023-12-11 20:29 UTC, merged