T8S3-20 Crear modelo y repositorio de Transactions
alkemyTech/OT8-3-Server pull request #7
Opened 2023-12-03 17:52 UTC by leorivero

2023-12-04 17:29 UTC, PsyBrainy commented on pom.xml
> +        <dependency>
por que usas jakarta si podes usar GenerationType.IDENTITY;??

2023-12-04 18:39 UTC, leorivero91 commented on pom.xml
> +        <dependency>
Como pude acceder a la versión Ultimate de Intellij Idea gracias al mail de la cuenta .edu por un año, y Jakarta se encuentra solo para esa versión, elegí esa opción para aprovecharla.
Si es mas útil con GenerationType.IDENTITY lo modifico

2023-12-04 22:44 UTC, PsyBrainy commented on pom.xml
> +        <dependency>
mas alla de la utilidad, deberiamos evitar tener mas dependencia externas. de esta manera vamos a tener mayor control de codigo y no va a haber ningun posible problema de compatibilidad

2023-12-04 22:52 UTC, Tilk1 commented on src/main/java/com/alkemy/wallet/repository/TransactionsRepository.java
> +import javax.transaction.Transaction;
aca debe ser jakarta

2023-12-04 23:01 UTC, Tilk1 requested changes
Quita la dependencia de jakarta que no es necesaria. Spring ya trae jakarta persistance

Cambia la linea que usa javax por jakarta `import javax.transaction.Transaction;`

El model esta mal definido no compila la aplicacion, dice que hay problemas con los enums.

No les pongas nombres a las columnas en mayusculas, deja los nombres por defecto sin las anotaciones

2023-12-04 23:50 UTC, leorivero commented
ya realice los cambios

2023-12-05 00:44 UTC, PsyBrainy commented on src/main/java/com/alkemy/wallet/repository/TransactionsRepository.java
> +import javax.transaction.Transaction;
deberias importarlo de tu modelo Transation, ahi estas haiendo referencia a otra importacion

2023-12-05 00:46 UTC, PsyBrainy commented on src/main/java/com/alkemy/wallet/repository/TransactionsRepository.java
> +import jakarta.transaction.Transaction;
esto no deberia estar, tenes que importar tu modelo de Transaction y borrar la dependencia de jakarta

2023-12-05 00:46 UTC, PsyBrainy commented on pom.xml
> +		<dependency>
estas lineas borralas, lo de jakarta no deberia ir

2023-12-05 00:47 UTC, PsyBrainy commented on src/main/java/com/alkemy/wallet/repository/TransactionsRepository.java
> +import javax.transaction.Transaction;
@Tilk1 cuidado con eso, no estamos usando jakarta en el proyecto

2023-12-05 01:03 UTC, leorivero commented on src/main/java/com/alkemy/wallet/repository/TransactionsRepository.java
> +import javax.transaction.Transaction;
ahora si creo que lo importe como modelo

2023-12-05 01:03 UTC, leorivero commented on src/main/java/com/alkemy/wallet/repository/TransactionsRepository.java
> +import jakarta.transaction.Transaction;
ya borre lo que tenia que ver con jakarta, creo que esta vez quedo

2023-12-05 01:16 UTC, PsyBrainy approved these changes

2023-12-05 01:17 UTC, PsyBrainy approved these changes

2023-12-05 02:27 UTC, Tilk1 approved these changes

2023-12-05 02:27 UTC, merged